/*
 * This file was auto-generated by speedy-antlr-tool v{{__version__}}
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "{{parser_basename}}BaseVisitor.h"
#include "speedy_antlr.h"

class SA_{{grammar_name}}Translator : public {{parser_basename}}BaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
{%- for d in context_data if not d.is_label_parent %}
    PyObject *{{d.Rule_name}}Context_cls = NULL;
{%- endfor %}

    public:
    SA_{{grammar_name}}Translator(speedy_antlr::Translator *translator);
    ~SA_{{grammar_name}}Translator();

{%- for d in context_data if not d.is_label_parent %}
    antlrcpp::Any visit{{d.Rule_name}}({{grammar_name}}Parser::{{d.Rule_name}}Context *ctx);
{% endfor %}
};
